# Generated by Django 3.2.8 on 2021-12-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModels',
            fields=[
                ('NewsID', models.AutoField(primary_key=True, serialize=False)),
                ('NewsDate', models.DateTimeField(auto_now_add=True)),
                ('NewsTitle', models.CharField(max_length=100)),
                ('NewsContent', models.CharField(max_length=5000)),
            ],
        ),
    ]
