# Generated by Django 3.2.8 on 2021-12-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodels',
            options={'ordering': ['NewsDate'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
