# Generated by Django 3.2.8 on 2021-12-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_newsmodels_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodels',
            options={'ordering': ['-NewsID'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='newsmodels',
            name='NewsPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/news/'),
        ),
    ]
