# Generated by Django 3.2.8 on 2021-12-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20211212_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodels',
            name='NewsContentShort',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
