# Generated by Django 3.2.8 on 2021-12-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_newsmodels_newscontentshort'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdModels',
            fields=[
                ('AdID', models.AutoField(primary_key=True, serialize=False)),
                ('AdDate', models.DateTimeField(auto_now_add=True)),
                ('AdTitle', models.CharField(max_length=100)),
                ('AdContent', models.CharField(max_length=5000)),
                ('AdPhoto', models.ImageField(blank=True, null=True, upload_to='images/ad/')),
                ('AdContentShort', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-AdID'],
            },
        ),
        migrations.AlterField(
            model_name='newsmodels',
            name='NewsContentShort',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
