# Generated by Django 3.2.8 on 2021-12-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20211212_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admodels',
            name='AdContentShort',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admodels',
            name='AdPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/news/'),
        ),
        migrations.AlterField(
            model_name='newsmodels',
            name='NewsContentShort',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
