# Generated by Django 3.2.8 on 2021-12-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_auto_20211213_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawsModels',
            fields=[
                ('LawID', models.AutoField(primary_key=True, serialize=False)),
                ('LawDate', models.DateTimeField(auto_now_add=True)),
                ('LawTitle', models.CharField(max_length=100)),
                ('LawFile', models.FileField(blank=True, null=True, upload_to='laws/')),
            ],
            options={
                'verbose_name': 'Нормативный документ',
                'verbose_name_plural': 'Нормативные документы',
            },
        ),
        migrations.AlterModelOptions(
            name='admodels',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='newsmodels',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
